### ISSUE TITLE
5.7 Improvement. Split main project into three projects

### ISSUE THREAD

**Issue by SergeyMokin** [epambrest/capacity#90]
Description
----------------------------------------------------------------------------
As a developer I want to see main project split into three projects.

Solution
----------------------------------------------------------------------------
Split main project into Web, Bussiness, Data projects. 
Also split test project into projects for which them created (Web/Bussiness/Data)

How it looks now:
![image](https://user-images.githubusercontent.com/18099408/99809601-93fc5680-2b53-11eb-854d-e82e2ad1baf8.png)

NOTE: Naming like this Teams.Web / Teams.Bussiness / Teams.Data, Naming Test: Teams.Bussiness.Tests/Teams.Data.Tests

**SP 2**

**Comment by Artem-Halvita** [comment]
@desenzo , why bug label?
